[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "ed0fa87385f36e9eeef69d0acb70bd5cf88cee67"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "29c5a608861cc9c06d3f86852a7d7b1a868de2d7ab90d4ff625aeebfb9383390"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "c3865d8b1827775f9569e7bc11f49f7d6989ec48"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "bad9a353330d9f409fe9db790da5701074112f804073506bb2808dd97b940b3c"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "699e2ff34411eeecec59dc75b482ad8f9c25ca16"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "7f455c2b498a6197db7f00d636899ed0fb20ce152f1b1573a3ee524ee98b1b80"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab28e30c68fb3ee9fbf9ebbe9ab2c44548c8aa5f"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "d86de4cd9e8264ff8dff1b2ec52b8fd2dbb9a01acb6c23ad73e38695d2de98e6"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "c9e1eca99029470a8b6e89094930d9a0a5550c17"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "1a357b1e44f7ec7c2da62461a4180d8d8b599dd06045e7e2b83cd7f93972d6d7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "207eaf0e37af6a303baf5b38776a53a2d225e216"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "216a1c6d178e0494ac488f3310e600ef17c62ce38d43e9b14557d1f16f3637f7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "7f59d1ceccd777bdc19709ab9918a2e1b3ce698c"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "58344f7047aceefa44e9aef552b9b84ae3d16fded31a5c6ba9b63abc2c269f43"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "cce6f7e2b5bb575a13eac72dc0d0db828677cf2b"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "bc5d90c9286f7c44dac7d44fabe815ec87e661a4b1b3e5b51c4a71890680b2d1"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-pc-windows-gnullvm.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "002276e90ea55e17700d23dc922a10230789d731"
lazy = true
os = "netbsd"

    [[RustToolChain.download]]
    sha256 = "4666e7d6621a2d90220fca136e9f6e6b437e5159ec7ce008fd95a9f2a0aff909"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-netbsd.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "506f630e28b1f38fae0830aa387ca47c565f3225"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "6bafa3b5367019c576751741295e06717f8f28c9d0e6631dcb9496cd142a386a"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-aarch64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "cc4cbe6adc58f9ebce98af5f0ee2364e7ec16ce5"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "5d4bd3705d6cb005449a22aa74ac073886a0e6a6026d2fc24d53b0acaca60255"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-x86_64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "0b241de8f5bd66ffb66eac97ffbe9679ac324d5e"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "ef2a03ba7b314c32c464f7d1f51053808b270fa46e0334c3962751e63c5a607a"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "6059bdacc2b3cdaa064721ae3c05b560a20dbe50"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "fa99eb4e823fdeb8ee25e486c7973b4803013ac68c64e8f74880da788db9739c"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "0e73065103b4ece65bcd0442f05f787401676102"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "bbe822f0aae2c1d31fa950a78446d4749e07ed67e974f87bf0c69146df2a9d9c"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a46529d518672a609a11348ff93e360b49f0539c"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "a33bb432cf0ff752a628be3d73670ae053be8675f39414af1f17ada62257449a"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-arm-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79f7ac6b990d0bc5be69131546589751e7db4603"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "0177f471c457b0a29ff81bf99d1078b676d652e6a7ebb31dfbeceb63a274e38c"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "d5c248cee58f793a3d6804436dfb8dd24d28f43a"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "59dfda4a3ba76113406ce80c802161ec669da49d5b7c0214abc5b99bff633e39"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "cf25ec768c49b3bc9cf73b1fd37f8b1e8636aa6d"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "4c2e2697c4911d32bf16dc7361f4205a08aeb557a3843403de1c554cd09ae601"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "7f09faeeb73c965116b11226fdbbac12e8bff757"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "5a6c766ce05ad7229aadbb365bad2c9c809c9e378706f123c156821fe6ab2711"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-x86_64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "4b102255ee0d9e687d268a6b252fd818e40c039a"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "859d2e973ba1b0106aaeb5df7db72673cb82b9de417339e28ae9b5074756db5b"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-aarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "c8280a5d231563be68df092469ed108947598379"
lazy = true
os = "freebsd"

    [[RustToolChain.download]]
    sha256 = "61c78738716543c1e217c813bab3ac58d0524afbaeb5fbd40dfdcd3f2c3992a2"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-x86_64-unknown-freebsd.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "9209f2dc5244168bcfbda14151faee5331b7fa51"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "c79a135d751d19823c930492628c5008b8fcfae2bf753b4b4b80e1e7b9915f9b"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-i686-pc-windows-msvc.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "2cda736c147b5353295292f9559a25c8cf833b08"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "08656839d486c823ea8ff59fc61aa7a7eae6600fa38fa7d9b426544cb7761eaf"
    url = "https://static.rust-lang.org/dist/rust-1.93.1-x86_64-pc-windows-msvc.tar.gz"
