[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "ed0fa87385f36e9eeef69d0acb70bd5cf88cee67"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "29c5a608861cc9c06d3f86852a7d7b1a868de2d7ab90d4ff625aeebfb9383390"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "c3865d8b1827775f9569e7bc11f49f7d6989ec48"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "bad9a353330d9f409fe9db790da5701074112f804073506bb2808dd97b940b3c"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "699e2ff34411eeecec59dc75b482ad8f9c25ca16"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "7f455c2b498a6197db7f00d636899ed0fb20ce152f1b1573a3ee524ee98b1b80"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab28e30c68fb3ee9fbf9ebbe9ab2c44548c8aa5f"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "d86de4cd9e8264ff8dff1b2ec52b8fd2dbb9a01acb6c23ad73e38695d2de98e6"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "c9e1eca99029470a8b6e89094930d9a0a5550c17"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "1a357b1e44f7ec7c2da62461a4180d8d8b599dd06045e7e2b83cd7f93972d6d7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "207eaf0e37af6a303baf5b38776a53a2d225e216"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "216a1c6d178e0494ac488f3310e600ef17c62ce38d43e9b14557d1f16f3637f7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "7f59d1ceccd777bdc19709ab9918a2e1b3ce698c"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "58344f7047aceefa44e9aef552b9b84ae3d16fded31a5c6ba9b63abc2c269f43"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "cce6f7e2b5bb575a13eac72dc0d0db828677cf2b"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "bc5d90c9286f7c44dac7d44fabe815ec87e661a4b1b3e5b51c4a71890680b2d1"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-pc-windows-gnullvm.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "002276e90ea55e17700d23dc922a10230789d731"
lazy = true
os = "netbsd"

    [[RustToolChain.download]]
    sha256 = "4666e7d6621a2d90220fca136e9f6e6b437e5159ec7ce008fd95a9f2a0aff909"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-netbsd.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "037ccf79957413791c27aa69e395ebe155143777"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "c080e506af9cba3ca9472c17d989c2d8d5bcfc818eb5e196c77beee982788b50"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-aarch64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "b9a4c4b764c55e6f923cd0eedd472c6e6e26d445"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "c19cc27b3387e2dfe7eb4b5becc75ab5acf348b2a7f2142ad3716d93a0abaa2a"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-x86_64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "dc81aaabef8c15564e2eea348127ce7106fb7de4"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "9a3ef03fa419d662fbaf9b152a81db96379781771e6853ca06e31215fb177449"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "525bec725a4e5379c42affd914a0e9d28373c6ea"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "b177534946e6e5422d8a75398b39625c08eabad675c08bd3d6565d3ba90c8450"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "b646d18c0853d98f1649c1a29e0818ea77c0be18"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "212cebf45b0669b2176eb08ffa17c90b07f9de2689d6aae3604d78699fa4f5c2"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d6dc2932991409edd5d7acc332fde1612e74ffd"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "c0c4b52bf5614dfcf6b9e94876f97509c71831fc09b8f0f0e228e13ce896ea92"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-arm-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "daef792430dea0aa7395ea889b4cedb05cf793f3"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "59320d46850c750b0a0d3e49939c00c3eed9917fab9a633300fb4d04bd8cfebc"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "36863161f1a94f546c21d57e809e8105e465d6a7"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "4cde26acb968f98fdb2f7f52e7f78b75a24afdea38abed7217e1cd02c6acbe06"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "97def93d78e8d771cb7f68dd873064a0957b5daf"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "b4c54315491239d2a4816535cea22a57ad1021e2529812ccfc938e64c53da276"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "fb62e88e017cb9bd0bfb8e4037894813631dec0d"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "12404d68457d3344877fbba3fde2c68743cd200fc70475451568e18076cc2a3d"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-x86_64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "4e040b9ee7ebd072314d485246f65fa3754b5f1f"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "9e936f24cfd76db8a45ab352919336978531c0fb4eab7a7bdecc76b9562fcbdb"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-aarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "6c8a54fb0897d8bb7fb37a2d0d01a7dc823efd7d"
lazy = true
os = "freebsd"

    [[RustToolChain.download]]
    sha256 = "8f5f247b7195a8925c092949c4eea96a6228d67e643dc10d97b1ed7c17e4c433"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-x86_64-unknown-freebsd.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "334cc1bef1b9bcbc3d599e87fb4b99260d2f45ab"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "b3b4fd634c2754a60369d3e1f2756068fc2cba9a1ce085b53f53c3372a60d315"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-i686-pc-windows-msvc.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "315f5763fa1509c0fb7d6bf4df9ab72448eab9ff"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "0f96cd17def778e6f60c1c9bef6a08b9557d797146c7b543c93b95df5cbe64ee"
    url = "https://static.rust-lang.org/dist/rust-1.96.1-x86_64-pc-windows-msvc.tar.gz"
